//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenderosORM_EF_existeBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUTA
    {
        public int IDRUTA { get; set; }
        public string NOMBRE { get; set; }
        public decimal DISTANCIA { get; set; }
        public int DESNIVEL { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string LOCALIZACION { get; set; }
        public Nullable<int> DIFICULTAD { get; set; }
    
        public virtual NIVELESDIFICULTAD NIVELESDIFICULTAD { get; set; }
    }
}
