//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenderosORM_EF_existeBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SenderosEntities2 : DbContext
    {
        public SenderosEntities2()
            : base("name=SenderosEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NIVELESDIFICULTAD> NIVELESDIFICULTADs { get; set; }
        public virtual DbSet<RUTA> RUTAS { get; set; }
    
        public virtual int spNuevoSendero(string nOMBRE, Nullable<decimal> dISTANCIA, Nullable<int> dESNIVEL, Nullable<System.DateTime> fECHA, string lOCALIZACION, Nullable<int> dIFICULTAD)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var dISTANCIAParameter = dISTANCIA.HasValue ?
                new ObjectParameter("DISTANCIA", dISTANCIA) :
                new ObjectParameter("DISTANCIA", typeof(decimal));
    
            var dESNIVELParameter = dESNIVEL.HasValue ?
                new ObjectParameter("DESNIVEL", dESNIVEL) :
                new ObjectParameter("DESNIVEL", typeof(int));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            var lOCALIZACIONParameter = lOCALIZACION != null ?
                new ObjectParameter("LOCALIZACION", lOCALIZACION) :
                new ObjectParameter("LOCALIZACION", typeof(string));
    
            var dIFICULTADParameter = dIFICULTAD.HasValue ?
                new ObjectParameter("DIFICULTAD", dIFICULTAD) :
                new ObjectParameter("DIFICULTAD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spNuevoSendero", nOMBREParameter, dISTANCIAParameter, dESNIVELParameter, fECHAParameter, lOCALIZACIONParameter, dIFICULTADParameter);
        }
    
        public virtual ObjectResult<spVerNiveles_Result> spVerNiveles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spVerNiveles_Result>("spVerNiveles");
        }
    
        public virtual ObjectResult<spVerSendero_Result> spVerSendero(Nullable<int> iDRuta)
        {
            var iDRutaParameter = iDRuta.HasValue ?
                new ObjectParameter("IDRuta", iDRuta) :
                new ObjectParameter("IDRuta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spVerSendero_Result>("spVerSendero", iDRutaParameter);
        }
    
        public virtual ObjectResult<spVerSenderos_Result> spVerSenderos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spVerSenderos_Result>("spVerSenderos");
        }
    
        public virtual ObjectResult<RUTA> spVerSenderos1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RUTA>("spVerSenderos1");
        }
    
        public virtual ObjectResult<RUTA> spVerSenderos1(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RUTA>("spVerSenderos1", mergeOption);
        }
    }
}
