//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestamosORM_EF_modelFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrestamosModelContainer : DbContext
    {
        public PrestamosModelContainer()
            : base("name=PrestamosModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuarios> UsuariosSet { get; set; }
        public virtual DbSet<Articulos> ArticulosSet { get; set; }
        public virtual DbSet<Prestamos> PrestamosSet { get; set; }
    }
}
