//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestamosORM_EF_modelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        public int IdPrestamo { get; set; }
        public int Articulos_IdArticulo { get; set; }
        public int Usuarios_IdUser { get; set; }
    
        public virtual Articulos ArticulosSet { get; set; }
        public virtual Usuarios UsuariosSet { get; set; }
    }
}
